// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK7p5MGcXtSgUgu0Rd8YwSTWUzAs2mS6U',
    appId: '1:1037775543222:web:522593e33885574aabff17',
    messagingSenderId: '1037775543222',
    projectId: 'dietrx-6c017',
    authDomain: 'dietrx-6c017.firebaseapp.com',
    storageBucket: 'dietrx-6c017.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8E3hi7R8-pbmN7oJ6LikK1wfXZNj44B0',
    appId: '1:1037775543222:android:ebd457c3f1cc6295abff17',
    messagingSenderId: '1037775543222',
    projectId: 'dietrx-6c017',
    storageBucket: 'dietrx-6c017.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWO_wPftNZb9_4fEO8BLaMIrXtZ1x8j4M',
    appId: '1:1037775543222:ios:00bf3d123edb4dd5abff17',
    messagingSenderId: '1037775543222',
    projectId: 'dietrx-6c017',
    storageBucket: 'dietrx-6c017.firebasestorage.app',
    iosBundleId: 'com.example.dietrx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWO_wPftNZb9_4fEO8BLaMIrXtZ1x8j4M',
    appId: '1:1037775543222:ios:00bf3d123edb4dd5abff17',
    messagingSenderId: '1037775543222',
    projectId: 'dietrx-6c017',
    storageBucket: 'dietrx-6c017.firebasestorage.app',
    iosBundleId: 'com.example.dietrx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK7p5MGcXtSgUgu0Rd8YwSTWUzAs2mS6U',
    appId: '1:1037775543222:web:bde6fa3a3ec65cfdabff17',
    messagingSenderId: '1037775543222',
    projectId: 'dietrx-6c017',
    authDomain: 'dietrx-6c017.firebaseapp.com',
    storageBucket: 'dietrx-6c017.firebasestorage.app',
  );
}
